name: json2model
description: This library generates a model object corresponding to a JSON string by executing commands in code.
version: 1.0.0
author: venshine<venshine@163.com,venshine.cn@gmail.com>
homepage: https://github.com/venshine/json2model

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

executables:
  json2model:

dev_dependencies:
  effective_dart: ^1.3.0
  pedantic: ^1.9.0
  test: ^1.14.4
